---
# https://redhat-cop.github.io/automation-good-practices/#_platform_specific_variables

- name: Ensure ansible_facts required by role have been gathered
  ansible.builtin.setup:
    gather_subset: "{{ __hello_world_required_facts_subsets }}"
  when: not ansible_facts.keys() | list | intersect(__hello_world_required_facts) == __hello_world_required_facts

- name: Set platform/version specific variables
  ansible.builtin.include_vars: "{{ __hello_world_vars_file }}"
  loop:
    - "{{ ansible_facts['os_family'] }}.yml"
    - "{{ ansible_facts['distribution'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_major_version'] }}.yml"
    - "{{ ansible_facts['distribution'] }}_{{ ansible_facts['distribution_version'] }}.yml"
  vars:
    __hello_world_vars_file: "{{ role_path }}/vars/{{ item }}"
  when: __hello_world_vars_file is file
