---
# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_reuse_roles.html#role-argument-validation

# NOTE: hello_world argument validation
# argument_specs:
#   main:
#     short_description: The main entry point for the hello_world role.
#     options:
#       hello_world_int:
#         type: "int"
#         required: false
#         default: 42
#         description: "The integer value, defaulting to 42."
#
#       hello_world_str:
#         type: "str"
#         required: true
#         description: "The string value"
