---
# NOTE: hello_world Default Playbook

- name: Run daleroux.hello_tam_blog.hello_world # noqa: role-name[path]
  hosts: "{{ target | default('all') }}"
  gather_facts: false
  roles:
    - ../roles/hello_world
